[project]
name = "objdet_converter"
version = "1.2.0"
requires-python = ">= 3.8"
dependencies = [
    "numpy",
    "opencv-python",
    "fire",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = [""]
[project.scripts]
objdet-conv = "objdet_converter.app:app"