[project]
name = "objdet_converter"
version = "1.0.0"
requires-python = ">= 3.7"
dependencies = [
    "numpy",
    "opencv-python"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["objdet_converter"]
exclude = [""]
namespaces = false  # true by default