[project]
name = "objdet_converter"
version = "1.1.0"
requires-python = ">= 3.8"
dependencies = [
    "numpy",
    "opencv-python"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = [""]